name: SSH Connect_OSTAD

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Beforessh
        run: |
          ip addr
  

      - name: Connect via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            # ১. /tmp ফোল্ডারে পুরানো ক্লোন থাকলে তা আগে মুছে ফেলা (এরর এড়ানোর জন্য)
            sudo rm -rf /tmp/system_frontend_react

            # ২. গিট দিয়ে নির্দিষ্ট রেপোজিটরি /tmp ফোল্ডারে ডাউনলোড করা
            git clone https://github.com/chintitomasud3/system_frontend_react.git /tmp/system_frontend_react

            # ৩. ডাউনলোড হওয়া ফোল্ডারে প্রবেশ করা
            cd /tmp/system_frontend_react

            # ৪. প্রজেক্টের ডিপেন্ডেন্সি ইনস্টল এবং বিল্ড করা
            npm install --production
            npm install vite
            npm run build

            # ৫. বিল্ড হওয়া ফাইলগুলো আসল ওয়েব ডিরেক্টরিতে (যেমন Nginx এর পাথে) কপি করা
            # (React অ্যাপ বিল্ড হলে সাধারণত dist অথবা build ফোল্ডার তৈরি হয়)
            sudo chown -R ubuntu:ubuntu /var/www/html/masud
            sudo chmod -R 755 /var/www/html/masud

            sudo cp -r dist/* /var/www/html/masud

            # ৬. এনজিনেক্স রিলোড করা
            sudo systemctl reload nginx

         
            
